-- =====================================================================
-- supabase/migrations/schema.sql
-- SINGLE source of truth for the React academic-profile app.
--
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor → New query),
-- then run storage.sql. Safe to re-run: CREATE IF NOT EXISTS + idempotent
-- policy/seed blocks. The RLS block at the bottom is what lets the logged-in
-- admin (an `authenticated` user) write from the browser — without it, admin
-- saves are silently rejected and never reach the public page.
--
-- This supersedes the old Django-era schema (the `site_pages` design). The
-- React app reads/writes `site_sections` + `custom_pages` instead, and expects
-- `teaching_courses.institution`, `news_items.visible`, `publications.visible`.
-- =====================================================================

-- ── 0. Drop the orphan table from the old Django schema ───────────────
-- The React app never reads `site_pages`; it only causes confusion. Safe to
-- remove. (Comment this out if you still want to keep it around.)
DROP TABLE IF EXISTS site_pages CASCADE;

-- ── 1. Core content tables ────────────────────────────────────────────

-- Single-row profile record
CREATE TABLE IF NOT EXISTS site_profile (
  id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name        text        NOT NULL DEFAULT '',
  name_alt         text                 DEFAULT '',
  title            text                 DEFAULT '',
  department_1     text                 DEFAULT '',
  department_2     text                 DEFAULT '',
  university       text                 DEFAULT '',
  address          text                 DEFAULT '',
  office           text                 DEFAULT '',
  phone            text                 DEFAULT '',
  email            text                 DEFAULT '',
  photo_url        text                 DEFAULT '',
  biography        text                 DEFAULT '',
  scholar_url      text                 DEFAULT '',
  researchgate_url text                 DEFAULT '',
  linkedin_url     text                 DEFAULT '',
  github_url       text                 DEFAULT '',
  orcid_url        text                 DEFAULT '',
  students_text    text                 DEFAULT '',
  students_email   text                 DEFAULT '',
  updated_at       timestamptz          DEFAULT now()
);

-- CV / résumé PDF link (uploaded to the public `profile` storage bucket)
ALTER TABLE site_profile ADD COLUMN IF NOT EXISTS cv_url text DEFAULT '';

CREATE TABLE IF NOT EXISTS news_items (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_date date,
  body       text    NOT NULL DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS visible boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS research_interests (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label      text   NOT NULL DEFAULT '',
  sort_order int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS education_entries (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  degree      text   NOT NULL DEFAULT '',
  institution text   NOT NULL DEFAULT '',
  sort_order  int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS publications (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  pub_id     text    NOT NULL DEFAULT '',
  pub_type   text    NOT NULL DEFAULT 'journal',
  citation   text    NOT NULL DEFAULT '',
  pdf_url    text             DEFAULT '',
  doi_url    text             DEFAULT '',
  slides_url text             DEFAULT '',
  award_note text             DEFAULT '',
  year       int,
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);
ALTER TABLE publications ADD COLUMN IF NOT EXISTS visible    boolean NOT NULL DEFAULT true;
ALTER TABLE publications ADD COLUMN IF NOT EXISTS citation   text             DEFAULT '';
ALTER TABLE publications ADD COLUMN IF NOT EXISTS award_note text             DEFAULT '';

CREATE TABLE IF NOT EXISTS teaching_courses (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label       text   NOT NULL DEFAULT '',
  institution text             DEFAULT '',
  sort_order  int    NOT NULL DEFAULT 0
);
ALTER TABLE teaching_courses ADD COLUMN IF NOT EXISTS institution text DEFAULT '';

CREATE TABLE IF NOT EXISTS awards (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  label      text   NOT NULL DEFAULT '',
  year       int,
  sort_order int    NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS service_entries (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category   text   NOT NULL DEFAULT '',
  label      text   NOT NULL DEFAULT '',
  sort_order int    NOT NULL DEFAULT 0
);

-- ── 2. Navigation + custom pages (used by the React admin) ────────────

-- Controls nav labels, order, and visibility per built-in section
CREATE TABLE IF NOT EXISTS site_sections (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug       text    NOT NULL UNIQUE,
  label      text    NOT NULL DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);

-- Extra pages added from the admin dashboard
CREATE TABLE IF NOT EXISTS custom_pages (
  id         bigint  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug       text    NOT NULL UNIQUE,
  title      text    NOT NULL DEFAULT '',
  content    text             DEFAULT '',
  sort_order int     NOT NULL DEFAULT 0,
  visible    boolean NOT NULL DEFAULT true
);

-- ── 3. Row-Level Security ─────────────────────────────────────────────
-- public can SELECT; logged-in (authenticated) users get full read/write.
-- THIS is what makes admin edits persist and show up on the public page.

ALTER TABLE site_profile       ENABLE ROW LEVEL SECURITY;
ALTER TABLE news_items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_entries  ENABLE ROW LEVEL SECURITY;
ALTER TABLE publications       ENABLE ROW LEVEL SECURITY;
ALTER TABLE teaching_courses   ENABLE ROW LEVEL SECURITY;
ALTER TABLE awards             ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_entries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_sections      ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_pages       ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  r   RECORD;
  tbl text;
BEGIN
  -- Drop every existing policy on all affected tables (handles any name)
  FOR r IN
    SELECT tablename, policyname FROM pg_policies
    WHERE schemaname = 'public'
    AND tablename IN (
      'site_profile','news_items','research_interests','education_entries',
      'publications','teaching_courses','awards','service_entries',
      'site_sections','custom_pages'
    )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;

  -- Recreate: public SELECT + authenticated full access
  FOREACH tbl IN ARRAY ARRAY[
    'site_profile','news_items','research_interests','education_entries',
    'publications','teaching_courses','awards','service_entries',
    'site_sections','custom_pages'
  ] LOOP
    EXECUTE format('CREATE POLICY "public_read" ON public.%I FOR SELECT USING (true)', tbl);
    EXECUTE format(
      'CREATE POLICY "auth_all" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)',
      tbl
    );
  END LOOP;
END $$;

-- ── 4. Seed site_sections (skip if already populated) ────────────────

INSERT INTO site_sections (slug, label, sort_order, visible)
SELECT slug, label, sort_order, visible FROM (VALUES
  ('biography',    'Biography',       1, true),
  ('news',         'News',            2, true),
  ('research',     'Research',        3, true),
  ('education',    'Education',        4, true),
  ('publications', 'Publications',    5, true),
  ('teaching',     'Teaching',        6, true),
  ('awards',       'Honors & Awards', 7, true),
  ('service',      'Service',         8, true)
) AS v(slug, label, sort_order, visible)
WHERE NOT EXISTS (SELECT 1 FROM site_sections)
ON CONFLICT (slug) DO NOTHING;

-- Storage bucket + its policies live in storage.sql — run that next.
